=== sorca-/WEBParsing/src/main/resources/electricalAppliances.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:tns="http://www.star4.in"
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.star4.in"
        elementFormDefault="qualified">

    <element name="appliance" type="tns:Appliance" abstract="true"/>
    <element name="local" type="tns:Local" abstract="true" substitutionGroup="tns:appliance"/>
    <element name="portable" type="tns:Portable" abstract="true" substitutionGroup="tns:appliance"/>
    <element name="hairdryer" type="tns:Hairdryer" substitutionGroup="tns:local"/>
    <element name="kettle" type="tns:Kettle" substitutionGroup="tns:local"/>
    <element name="media_center" type="tns:Media_Center" substitutionGroup="tns:local"/>
    <element name="photo_camera" type="tns:Photo_Camera" substitutionGroup="tns:portable"/>

    <element name="appliances">
        <complexType>
            <sequence>
                <element ref="tns:locals" minOccurs="1" maxOccurs="1"/>
                <element ref="tns:portables" minOccurs="1" maxOccurs="1"/>
            </sequence>
        </complexType>
    </element>

    <element name="locals">
        <complexType>
            <sequence>
                <element ref="tns:hairdryer" minOccurs="0" maxOccurs="unbounded"/>
                <element ref="tns:kettle" minOccurs="0" maxOccurs="unbounded"/>
                <element ref="tns:media_center" minOccurs="0" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="portables">
        <complexType>
            <choice>
                <element ref="tns:photo_camera" minOccurs="0" maxOccurs="unbounded"/>
            </choice>
        </complexType>
    </element>

    <complexType name="Appliance">
        <sequence>
            <element name="model" type="string" default="unknown"/>
            <element name="producer" type="string" default="unknown"/>
            <element name="voltage" type="positiveInteger"/>
            <element name="power" type="positiveInteger"/>
        </sequence>
        <attribute name="id" type="integer" use="required"/>
    </complexType>

    <complexType name="Local">
        <complexContent>
            <extension base="tns:Appliance">
                <sequence>
                    <element name="count-of-phase" type="positiveInteger"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Portable">
        <complexContent>
            <extension base="tns:Appliance">
                <sequence>
                    <element name="count-of-batteries" type="positiveInteger"/>
                    <element name="type-of-battery">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="LI_ION"/>
                                <enumeration value="PB"/>
                                <enumeration value="NI_MH"/>
                                <enumeration value="NI_CD"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Hairdryer">
        <complexContent>
            <extension base="tns:Local">
                <attribute name="count-of-modes" use="optional" default="N/A"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Kettle">
        <complexContent>
            <extension base="tns:Local">
                <attribute name="boil-time" type="positiveInteger" use="required"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Media_Center">
        <complexContent>
            <extension base="tns:Local">
                <attribute name="max-volume" type="positiveInteger" use="required"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Photo_Camera">
        <complexContent>
            <extension base="tns:Portable">
                <attribute name="resolution" type="positiveInteger" use="required"/>
            </extension>
        </complexContent>
    </complexType>

</schema>

=== sorca-/WEBParsing/src/main/resources/electricalAppliances.xml
<?xml version="1.1" encoding="UTF-8" ?>
<appliances
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.star4.in"
        xsi:schemaLocation="http://www.star4.in electricalAppliances.xsd">
    <locals>
        <hairdryer id="1" count-of-modes="4">
            <model>HPS32</model>
            <producer>Philips</producer>
            <voltage>220</voltage>
            <power>100</power>
            <count-of-phase>2</count-of-phase>
        </hairdryer>

        <hairdryer id="2" count-of-modes="2">
            <model>HSY55</model>
            <producer>SONY</producer>
            <voltage>220</voltage>
            <power>200</power>
            <count-of-phase>2</count-of-phase>
        </hairdryer>

        <kettle id="3" boil-time="110">
            <model>KPB43</model>
            <producer>Philips</producer>
            <voltage>220</voltage>
            <power>1000</power>
            <count-of-phase>2</count-of-phase>
        </kettle>

        <media_center id="4" max-volume="60">
            <model>MCS22</model>
            <producer>SONY</producer>
            <voltage>220</voltage>
            <power>100</power>
            <count-of-phase>2</count-of-phase>
        </media_center>
    </locals>

    <portables>
        <photo_camera id="5" resolution="12">
            <model>D5100</model>
            <producer>NIKON</producer>
            <voltage>6</voltage>
            <power>9</power>
            <count-of-batteries>4</count-of-batteries>
            <type-of-battery>LI_ION</type-of-battery>
        </photo_camera>
    </portables>
</appliances>
